export const ADD_SELECTED_PRODUCT = "ADD_SELECTED_PRODUCT";
export const ADD_TO_CART = "ADD_TO_CART";
export const CHANGE_DECREASE_PRODUCT = "CHANGE_DECREASE_PRODUCT";
export const CHANGE_INCREASE_PRODUCT = "CHANGE_INCREASE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
